### ISSUE TITLE
error SIE05-1484072050022

### ISSUE THREAD

**Issue by gtdewitt** [sentilo/sentilo#40]
Getting no GUI and error SIE05-1484072050022 when I try to start app at http://172.31.99.231:8080/sentilo-catalog-web/  .    Running the OVA in virtualbox on Windows 10 platform.

**Comment by dungtm007** [comment]
Hi @gtdewitt 

In my case, it is because of not starting mongoDb server yet.
Can you try?

Btw, I  also think the the error code is not explainable enough. Sentilo team should make it more detailed.

**Comment by carlospg79** [comment]
i solved the error repairing the MongoDB database as pointed by dungtm007.

you can do it with a `mongodb --dbpath /var/lib/mongodb --repair` 
after that, i needed to do a`chown mongodb /var/lib/mongodb/* -R` because i was logged as root.

after that, a `service mongodb start` works and you can access to the web.
